version: '2.1'
services:
  postgres:
      container_name: postgres
      image: postgres:12
      network_mode: host
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      volumes:
        - certificatesdb:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=postgres
        - POSTGRES_DB=certificatesdb
  app:
      container_name: CertExerciseApplication
      image: springbootapp:latest
      network_mode: host
      build:
        context: ./
        dockerfile: Dockerfile
      expose:
        - 8080
      ports:
        - 8080:8080
      depends_on:
        postgres:
          condition: service_healthy
volumes:
  certificatesdb: